---
title: "Untitled"
author: "Beau Coker"
date: "9/28/2018"
output: html_document
---

```{r, message=FALSE,warning=FALSE}
library(xgboost)
library(randomForest)
library(tidyverse)
library(lubridate)

source('functions.r')
```

```{r}
load("Table_construction.Rdata")
```

```{r}
features = features %>%
  # Add other useful information:
  inner_join(
    data_before %>% 
      select(person_id, screening_date, people) %>%
      unnest() %>%
      select(person_id, screening_date, race, sex, name),
    by = c("person_id","screening_date")
  ) %>%
  inner_join(features_on, by = c("person_id","screening_date")) %>%
  inner_join(outcomes, by = c("person_id","screening_date")) %>%
  
  # Create as many features as possible:
  mutate(
    raw_score = `Risk of Violence_raw_score`, # Adjust for violent/general
    decile_score = `Risk of Violence_decile_score`, # Adjust for violent/general
    p_juv_fel_count = pmin(p_juv_fel_count,2),
    p_felprop_violarrest = pmin(p_felprop_violarrest,5),
    p_murder_arrest = pmin(p_murder_arrest,3),
    p_felassault_arrest = pmin(p_felassault_arrest,3),
    p_misdemassault_arrest = pmin(p_misdemassault_arrest,3),
    #p_famviol_arrest = pmin(p_famviol_arrest,3),
    p_sex_arrest = pmin(p_sex_arrest,3),
    p_weapons_arrest = pmin(p_weapons_arrest,3),
    p_n_on_probation = pmin(p_n_on_probation,5),
    p_current_on_probation = pmin(p_current_on_probation,5),
    p_prob_revoke = pmin(p_prob_revoke,5),
    race_black = if_else(race=="African-American",1,0),
    race_white = if_else(race=="Caucasian",1,0),
    race_hispanic = if_else(race=="Hispanic",1,0),
    race_asian = if_else(race=="Asian",1,0),
    race_native = if_else(race=="Native American",1,0), # race == "Other" is the baseline
    
    # Subscales:
    vio_hist = p_juv_fel_count+
      p_felprop_violarrest+
      p_murder_arrest+
      p_felassault_arrest+
      p_misdemassault_arrest+
      #p_famviol_arrest+
      p_sex_arrest+
      p_weapons_arrest,
    history_noncomp=p_prob_revoke+
      p_probation+p_current_on_probation+
      p_n_on_probation,
    
    # Filters (TRUE for obserations to keep)
    filt1 = `Risk of Recidivism_decile_score` != -1, `Risk of Violence_decile_score` != -1, # Filter 1
    filt3 = !is.na(current_offense_date), # Filter 3
    filt4 = current_offense_date <= current_offense_date_limit, # Filter 4
    filt5 = p_current_age > 18 & p_current_age <= 70 # Filter 5
  )
```



## Fit age polynomial

```{r}
features_f_age = features %>%
  filter(filt1,filt5) %>%
  select(p_current_age, raw_score)

lb_age = features_f_age %>%
  group_by(p_current_age) %>%
  #arrange(raw_score, .by_group=TRUE) %>%
  arrange(raw_score) %>%
  top_n(n=-1, wt=raw_score) # Fit lower bound on smallest value

mdl_age = lm(raw_score ~ 
               I(p_current_age^4) + 
               I(p_current_age^3) + 
               I(p_current_age^2) + 
               p_current_age, 
             data=lb_age)

# More precision for paper
summary(mdl_age)
print("Coefficients:")
sprintf("%.20e",mdl_age$coefficients) # More precision for paper

## Add f(age) to features
features = features %>%
  mutate(
    f_age = predict(mdl_age, newdata=data.frame(p_current_age=p_current_age)),
    raw_score__f_age = raw_score - f_age,
    filt6 = raw_score >= f_age
  )
```


```{r}
## Age polynomial plot
xmin = 18
xmax = 70
xx = seq(xmin,xmax, length.out=1000)

ggplot()+
  geom_point(aes(x=p_current_age, raw_score), color="#619CFF",alpha=.3, data=features_f_age) +
  geom_line(aes(x=xx, predict(mdl_age, newdata=data.frame(p_current_age=xx))),color="#F8766D") +
  theme_bw()+
  xlim(xmin,xmax)+
  xlab("Age at COMPAS screening date") +
  ylab("Violent score") +
  theme(text = element_text(size=12),
        axis.text=element_text(size=12),
        legend.position="none")
```


```{r}
features %>%
  filter(filt1,filt5) %>%
  ggplot()+
  geom_histogram(aes(raw_score__f_age),bins=100)
```




```{r}
set.seed(83483)

# Sample LB
m = 150

lb_age_samp = features_f_age %>%
  group_by(p_current_age) %>%
  nest(.key="ages") %>%
  mutate(n = map(ages,nrow)) %>%
  unnest(n) %>%
  mutate(n_sample = map(n, ~min(.x,m))) %>%
  unnest(n_sample) %>%
  mutate(ages_sample = pmap(list(ages, n, n_sample), ~ ..1[sample(1:..2,..3),])) %>%
  mutate(min_raw_score = map(ages_sample, ~min(.x$raw_score))) %>%
  unnest(min_raw_score)

# Regress
mdl_age_samp = lm(min_raw_score ~ 
                    I(p_current_age^4) + 
                    I(p_current_age^3) + 
                    I(p_current_age^2) + 
                    p_current_age, 
                  data=lb_age_samp)

## Add f(age) to features
#features = features %>%
#  mutate(
#    f_age_samp = predict(mdl_age, newdata=data.frame(p_current_age=p_current_age))
#  )


## Age polynomial plot
xmin = 18
xmax = 70
xx = seq(xmin,xmax, length.out=1000)


lb = lb_age_samp %>% select(p_current_age, ages_sample) %>% unnest()

ggplot()+
  geom_point(aes(x=p_current_age, raw_score), color="#619CFF",alpha=.3, data=features_f_age) +
  geom_point(aes(x=p_current_age, raw_score), color="black",alpha=1, data=lb) +
  geom_point(aes(x=p_current_age, min_raw_score), color="green",alpha=1, data=lb_age_samp) +
  geom_line(aes(x=xx, predict(mdl_age_samp, newdata=data.frame(p_current_age=xx))),color="green") +
  geom_line(aes(x=xx, predict(mdl_age, newdata=data.frame(p_current_age=xx))),color="#F8766D") +
  theme_bw()+
  xlim(xmin,xmax)+
  xlab("Age at COMPAS screening date") +
  ylab("Violent score") +
  theme(text = element_text(size=12),
        axis.text=element_text(size=12),
        legend.position="none")
```




```{r}
ggplot(data=lb_age_samp, aes(x=p_current_age, y=n)) +
  geom_point() +
  ylab("Number of observations for this age") +
  theme_bw()
```

Quantile regression

```{r}
plot_quantile_reg <- function(alpha, features_f_age){
  
  features_age_quan = features_f_age %>%
    group_by(p_current_age) %>%
    nest(.key="ages") %>%
    mutate(n = map(ages,nrow)) %>%
    unnest(n) %>%
    mutate(score_quan = map(ages, ~quantile(.x$raw_score,probs=alpha))) %>%
    unnest(score_quan)
  
  mdl_age_quan = lm(score_quan ~ 
                      I(p_current_age^4) + 
                      I(p_current_age^3) + 
                      I(p_current_age^2) + 
                      p_current_age, 
                    data=features_age_quan)
  
  ## Age polynomial plot
  xmin = 18
  xmax = 70
  xx = seq(xmin,xmax, length.out=1000)
  
  p = ggplot()+
    geom_point(aes(x=p_current_age, raw_score), color="#619CFF",alpha=.3, data=features_f_age) +
    geom_point(aes(x=p_current_age, score_quan), color="#F8766D",alpha=1, data=features_age_quan) +
    geom_line(aes(x=xx, predict(mdl_age_quan, newdata=data.frame(p_current_age=xx))),color="#F8766D") +
    theme_bw()+
    xlim(xmin,xmax)+
    xlab("Age at COMPAS screening date") +
    ylab("Violent score") +
    ggtitle(paste("Quantile =",alpha))
  theme(text = element_text(size=12),
        axis.text=element_text(size=12),
        legend.position="none")
  
  return(p)
}
```


```{r}
plot_quantile_reg(alpha=.25, features_f_age)
```


```{r}

features_age_quan = features_f_age %>%
  group_by(p_current_age) %>%
  nest(.key="ages") %>%
  mutate(n = map(ages,nrow)) %>%
  unnest(n) %>%
  mutate(score_quan = map(ages, ~quantile(.x$raw_score,probs=alpha))) %>%
  unnest(score_quan)

mdl_age_quan = lm(score_quan ~ 
                    I(p_current_age^4) + 
                    I(p_current_age^3) + 
                    I(p_current_age^2) + 
                    p_current_age, 
                  data=features_age_quan)

## Age polynomial plot
xmin = 18
xmax = 70
xx = seq(xmin,xmax, length.out=1000)

p = ggplot()+
  geom_point(aes(x=p_current_age, raw_score), color="#619CFF",alpha=.3, data=features_f_age) +
  geom_point(aes(x=p_current_age, score_quan), color="#F8766D",alpha=1, data=features_age_quan) +
  geom_line(aes(x=xx, predict(mdl_age_quan, newdata=data.frame(p_current_age=xx))),color="#F8766D") +
  theme_bw()+
  xlim(xmin,xmax)+
  xlab("Age at COMPAS screening date") +
  ylab("Violent score") +
  ggtitle(paste("Quantile =",alpha))
theme(text = element_text(size=12),
      axis.text=element_text(size=12),
      legend.position="none")


```













```{r}
q = c(0,.25,.5,.75)


## Age polynomial plot
xmin = 18
xmax = 70
xx = seq(xmin,xmax, length.out=1000)

p = ggplot()+
  geom_point(aes(x=p_current_age, raw_score), color="#619CFF",alpha=.3, data=features_f_age) +
  theme_bw()+
  xlim(xmin,xmax)+
  xlab("Age at COMPAS screening date") +
  ylab("Violent score") +
  ggtitle(paste("Quantile ="))
theme(text = element_text(size=12),
      axis.text=element_text(size=12),
      legend.position="none")


for (i in 1:length(q)) {
  features_age_quan = features_f_age %>%
    group_by(p_current_age) %>%
    nest(.key="ages") %>%
    mutate(n = map(ages,nrow)) %>%
    unnest(n) %>%
    mutate(score_quan = map(ages, ~quantile(.x$raw_score,probs=q[i]))) %>%
    unnest(score_quan)
  
  mdl_age_quan = lm(score_quan ~ 
                      I(p_current_age^4) + 
                      I(p_current_age^3) + 
                      I(p_current_age^2) + 
                      p_current_age, 
                    data=features_age_quan)
  
  yy = predict(mdl_age_quan, newdata=data.frame(p_current_age=xx))
  
  p = p + 
    geom_line(aes(x=xx, y=yy),color="#F8766D") +
    geom_point(aes(x=p_current_age, y=score_quan), color="#F8766D",alpha=1, data=features_age_quan)
  
}

p
```




```{r}
q = c(0,.25,.5,.75, 1)

features_age_quan = features_f_age %>%
  group_by(p_current_age) %>%
  nest(.key="ages") %>%
  mutate(n = map(ages,nrow)) %>%
  unnest(n)

## For plot
xmin = 18
xmax = 70
lines = as.tbl(data.frame(x=seq(xmin,xmax, length.out=1000)))


for (i in 1:length(q)) {
  qi = paste0("q",i)
  
  features_age_quan =  features_age_quan %>%
    mutate(qi = map(ages, ~quantile(.x$raw_score,probs=q[i]))) %>%
    unnest(qi)
  
  mdl_age_quan = lm(qi ~ 
                      I(p_current_age^4) + 
                      I(p_current_age^3) + 
                      I(p_current_age^2) + 
                      p_current_age, 
                    data=features_age_quan)
  
  lines = lines %>%
    mutate(paste0("q",i) = predict(mdl_age_quan, newdata=data.frame(p_current_age=x)))
  
}


```

```{r}

features_age_quan = features_f_age %>%
  group_by(p_current_age) %>%
  nest(.key="ages") %>%
  mutate(n = map(ages,nrow)) %>%
  unnest(n)

quan_list = c(0,.25,.5,.75, 1)

score_quan = map_dfc(quan_list, function(q) {
  
  features_age_quan %>%
    mutate(score_quan = map(ages, ~quantile(.x$raw_score,probs=q))) %>%
    unnest(score_quan) %>%
    select(score_quan)
}
)

quan_fits = map(score_quan,
         ~ lm(y ~ I(x^4) + I(x^3) + I(x^2) + x, 
              data=data.frame(y = .x , x=features_age_quan$p_current_age))
)

xmin = 18
xmax = 70
xx = seq(xmin,xmax, length.out=1000)

quan_lines = map_dfc(quan_fits, ~ predict(.x, newdata=data.frame(x=xx)))


quan_lines = quan_lines %>% mutate(xx=xx)
score_quan = score_quan %>% mutate(p_current_age = features_age_quan$p_current_age)


quan_lines_long = gather(quan_lines, key="quan",value="quan_score",score_quan:score_quan4)
score_quan_long = gather(score_quan, key="quan",value="quan_score",score_quan:score_quan4)
```

```{r}
p = ggplot()+
  geom_point(aes(x=p_current_age, raw_score), color="#808080",alpha=.1, data=features_f_age) +
  geom_point(aes(x=p_current_age, y=quan_score, color=quan),alpha=1, data=score_quan_long) +
  geom_line(aes(x=xx, y=quan_score, color=quan),alpha=1, data=quan_lines_long) +
  theme_bw()+
  xlim(xmin,xmax)+
  xlab("Age at COMPAS screening date") +
  ylab("Violent score") +
  ggtitle(paste("Quantile ="))
theme(text = element_text(size=12),
      axis.text=element_text(size=12),
      legend.position="none")

p
```




----------------
For Cynthia

Beau, Can you try creating z = x+ epsilon and plotting x vs f(z) for different epsilon? Cheers, Cynthia


```{r}
sig2 = .1

features_f_age %>%
  mutate(z = p_current_age + rnorm(length(raw_score),0,sqrt(sig2))) %>%
  mutate(fz = predict(mdl_age, newdata=data.frame(p_current_age=z))) %>%
  ggplot(aes(x=p_current_age,y=fz)) +
  geom_point(alpha=.1) +
  theme_bw()
```


```{r}
sig2 = c(0,.4,.8,1.2,1.6,2)




lab = paste("sig2=",as.character(sig2))
names(lab) = c('s0','s1','s2','s3','s4','s5')

features_f_age %>%
  group_by(p_current_age) %>%
  summarize(raw_score_min = min(raw_score)) %>%
  mutate(s0 = p_current_age ) %>%
  mutate(s1 = p_current_age + rnorm(length(p_current_age),0,sqrt(sig2[1]))) %>%
  mutate(s2 = p_current_age + rnorm(length(p_current_age),0,sqrt(sig2[2]))) %>%
  mutate(s3 = p_current_age + rnorm(length(p_current_age),0,sqrt(sig2[3]))) %>%
  mutate(s4 = p_current_age + rnorm(length(p_current_age),0,sqrt(sig2[4]))) %>%
  mutate(s5 = p_current_age + rnorm(length(p_current_age),0,sqrt(sig2[5]))) %>%
  gather(key="sig2",value="z",s0:s5) %>%
  mutate(fz = predict(mdl_age, newdata=data.frame(p_current_age=z))) %>%
  ggplot(aes(x=p_current_age, y=fz)) +
  geom_point() +
  facet_grid(rows=vars(sig2), labeller=as_labeller(lab)) +
  theme_bw()
```


```{r}
ggsave("Figures/x_vs_f(z).pdf",height=5,width=4,units='in')
```

