---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(lubridate)
library(readr)
```

This notebook finds all the unique charge descriptions and joins them with Cynthia's annotations.

```{r}
compas <- read_csv("compas-analysis/compas-scores-two-years.csv")
```


```{r}
# Aggregate all charges (COMPAS, reoffense, violent reoffense)

charges <- rbind(
  compas %>% # Compas crimes
    filter(!is.na(c_charge_desc)) %>%
    select(charge_desc=c_charge_desc, 
           charge_degree = c_charge_degree,
           case_number = c_case_number,
           is_violent_recid,
           decile_score,
           v_decile_score,
           is_recid) %>%
    mutate(charge_desc = tolower(charge_desc),
           is_violent_recid = NA,
           is_recid = 0),
  compas %>% # Non-violent reoffenses
    mutate(charge_desc_agree = if_else(is.na(r_charge_desc) | is.na(vr_charge_desc), 
                                      FALSE, 
                                      r_charge_desc==vr_charge_desc)) %>%
    filter(!is.na(r_charge_desc),
           !charge_desc_agree) %>%
    select(charge_desc = r_charge_desc, 
           charge_degree = r_charge_degree,
           case_number = r_case_number,
           is_violent_recid, 
           decile_score,
           v_decile_score,
           is_recid) %>%
    mutate(charge_desc = tolower(charge_desc),
           charge_degree = substr(charge_degree,2,2),
           is_violent_recid = 0,
           decile_score = NA,
           v_decile_score = NA),
  compas %>% # Violent reoffenses
    filter(!is.na(vr_charge_desc)) %>%
    select(charge_desc=vr_charge_desc, 
           charge_degree = vr_charge_degree,
           case_number = vr_case_number,
           is_violent_recid,
           decile_score,
           v_decile_score,
           is_recid) %>%
    mutate(charge_desc = tolower(charge_desc),
           charge_degree = substr(charge_degree,2,2),
           decile_score = NA,
           v_decile_score = NA)
)

# Check case number counts
length(unique(charges$case_number))/nrow(charges)


length(unique(c(compas$c_case_number, compas$r_case_number, compas$vr_case_number)))/length(unique(charges$case_number))
```


```{r}
u_charges <- charges %>%
  group_by(charge_desc, charge_degree) %>%
  summarize(n_compas = sum(is_recid==0), 
            n_recid = sum(is_recid),
            is_violent_recid = max(is_violent_recid, na.rm=TRUE),
            avg_decile_score = mean(decile_score, na.rm=TRUE),
            avg_v_decile_score = mean(v_decile_score, na.rm=TRUE))
```


```{r}
# Now join with Cynthia's list
u_charges_cynthia <- read_csv('crime_descriptionsAnnotated.csv')

# Reformat
u_charges_cynthia <- cbind(
  u_charges_cynthia %>% 
    transmute(charge_desc=tolower(X1)),
  u_charges_cynthia %>%
    select(-X1,-X2,-X3) %>%
    mutate_all(funs(ifelse(.=="x",1,NA)))
)

# Remove duplicates
u_charges_cynthia <- u_charges_cynthia %>%
  group_by(charge_desc) %>%
  filter(row_number()==1)
```



```{r}
# Now joint together charge lists
u_charges_join <- left_join(u_charges, u_charges_cynthia, by="charge_desc")
```


```{r}
write_csv(u_charges_join, 'u_charges_join.csv', col_names = TRUE)
```