---
title: "Probation Features"
output: html_notebook
---

```{r}
setwd("../our_data/")
eventsdescrp_df<-read.csv("eventsdescrp_df1.csv")%>%
                    bind_rows(.,read.csv("eventsdescrp_df2.csv"))%>%
                    bind_rows(.,read.csv("eventsdescrp_df3.csv"))%>%
                    bind_rows(.,read.csv("eventsdescrp_df4.csv"))
```

```{r}
event_uid = eventsdescrp_df %>%
  filter(Description == "File Order Of Probation") %>%
  distinct(person_id, case_num, EventDate) %>%
  mutate(uid = row_number(), 
         Description = "File Order Of Probation")

eventsdescrp_df2 = left_join(eventsdescrp_df, event_uid, by = c("person_id" = "person_id", 
                                             "case_num" = "case_num",
                                             "EventDate" = "EventDate",
                                             "Description" = "Description"))
```

```{r}
eventsdescrp_df3 = eventsdescrp_df2 %>%
  mutate(uid = na.locf(uid))
```


```{r}
eventsdescrp_df3 = eventsdescrp_df2 %>%
  group_by(person_id) %>%
  arrange(EventDate) %>%
  mutate(uid = na.locf(uid))
```

----------------------

```{r}
### Local file paths

# ProPublica analysis
f_propub = "../compas-analysis/"

# Data we have pulled
f_our_data = "../our_data/"
```


```{r, message=FALSE, warning=FALSE}
eventsdescrp_df<-read_csv(paste0(f_our_data,"eventsdescrp_df1.csv"))%>%
                    bind_rows(.,read_csv(paste0(f_our_data,"eventsdescrp_df2.csv"))) %>%
                    bind_rows(.,read_csv(paste0(f_our_data,"eventsdescrp_df3.csv"))) %>%
                    bind_rows(.,read_csv(paste0(f_our_data,"eventsdescrp_df4.csv")))
```



```{r, message=FALSE}
feat = read_csv("features_vB.csv")
u_person_id = unique(feat$person_id)
rm(feat)
```

```{r}
## Connect to the database
db <- src_sqlite(paste0(f_propub,"compas.db"), create = TRUE)

## Convert tables to dataframes
charge_df <- tbl(db,"charge") %>%
  as_data_frame() %>%
  filter(charge_degree != "(0)",# These are very minor offenses (e.g. traffic tickets). We will never use them.
         person_id %in% u_person_id)  %>% 
  mutate(offense_date = as_date(ymd_hms(offense_date))) %>%
  arrange(person_id, offense_date) %>%
  group_by(person_id) %>%
  nest(.key = "charge")
  
## Cleanup
rm(db)
gc()
```


```{r}
event_on = c("File Order Of Probation")
event_off = c("File Order Of Revocation Of Probation",
              "File Expiration Of Probation",
              "File Order Granting Def Motion To Terminate Probation",
              "File Order Of Termination Of Probation")

prob = eventsdescrp_df %>% 
  filter(person_id %in% u_person_id) %>%
  mutate(prob_event = if_else(Description %in% event_on, "On",
                                if_else(Description %in% event_off, "Off", as.character(NA)))) %>%
  filter(!is.na(prob_event)) %>%
  mutate(EventDate = mdy(EventDate)) %>%
  arrange(person_id, EventDate) %>%
  group_by(person_id) %>%
  nest(.key="prob")
```

```{r}
df = inner_join(prob, charge_df, by = "person_id") ### CHANGE TO OTHER TYPE OF JOIN I THINK
```


```{r}
res = pmap_dfr(filter(df, person_id==8), .f=classify_charge)
```



```{r}
df %>%
  filter(person_id %in% c(4,8)) %>%
  mutate(n = map2(.x=prob,.y=charge,.f=classify_charge))
```

```{r}
count_on_probation(df$charge[[1]],df$prob[[1]])
```


```{r}
df %>%
  #filter(person_id %in% 1:100) %>%
  group_by(person_id) %>%
  mutate(n_on_probation = map2(charge,prob,.f=count_on_probation)) %>%
  unnest(n_on_probation)
```


```{r}
### Find person indices in two tables
#pid_prob = lapply(u_person_id, function(x) which(prob$person_id ==  x))
#pid_charge = lapply(u_person_id, function(x) which(charge_df$person_id ==  x))
```


```{r}
source("debug.R")
lapply(u_person_id, function(id) {
  classify_charge(filter(prob, person_id == id), filter(charge_df, person_id == id))
})
```


```{r}
source("debug.R")

i=2
nrow(filter(prob, person_id == u_person_id[i]))
nrow(filter(charge_df, person_id == u_person_id[i]))

classify_charge(filter(prob, person_id == u_person_id[i]),
                filter(charge_df, person_id == u_person_id[i]))
```





